### PR TITLE
Add the compatibility with Pug v3

### LINKED ISSUE #12: peerDependencies pug 's major version 2 is lower than pug's current version 3.

### PR DESCRIPTION
**Pull request by constgen**
Resolves #12 

Support both v2 and v3 of Pug

### CODE REVIEW

**Comment by constgen** [comment]
@yyx990803 Please can you merge this small and very useful fix

**Comment by Robula** [comment]
Move to Vue they said, it's modern. This repo is dead. Come on Evan! @yyx990803

**Comment by WTDuck** [comment]
> Move to Vue they said, it's modern. This repo is dead. Come on Evan! @yyx990803

ain't easy to be Evan, so instead of complaining, use @constgen fork in your project. 

`"pug-plain-loader": "github:constgen/pug-plain-loader#patch-1"`

**Comment by constgen** [comment]
I would recommend [@pointotech/pug-plain-loader](https://www.npmjs.com/package/@pointotech/pug-plain-loader) which is published to NPN by another user. I personally use it until this PR is merged

**Review by haoqunjiang — APPROVED** [review]

**Comment by haoqunjiang** [comment]
Published as v1.1.0

**Comment by constgen** [comment]
Thanks a lot

**Pull request merged**
